export const ACTION_TYPES = {

    // --- AUTH ---
    AUTHENTICATION_REQUEST: 'AUTHENTICATION_REQUEST',
    AUTHENTICATION_SUCCESS: 'AUTHENTICATION_SUCCESS',
    AUTHENTICATION_FAILURE: 'AUTHENTICATION_FAILURE',

    // --- LOGOUT ---
    USER_LOGOUT: 'USER_LOGOUT',
};