export const ACTION_TYPES = {

    // --- AUTH ---
    AUTHENTICATION_REQUEST: 'AUTHENTICATION_REQUEST',
    AUTHENTICATION_SUCCESS: 'AUTHENTICATION_SUCCESS',
    AUTHENTICATION_FAILURE: 'AUTHENTICATION_FAILURE',
    AUTHENTICATION_RESET: 'AUTHENTICATION_RESET',

    // --- FETCH ---
    FETCH_REQUEST: 'FETCH_REQUEST',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_FAILURE: 'FETCH_FAILURE',
    FETCH_DETAILS_SUCCESS: 'FETCH_DETAILS_SUCCESS',

    // --- LOGOUT ---
    USER_LOGOUT: 'USER_LOGOUT',


    // --- COURSE ---
    SET_COURSE_TO_ADD: 'SET_COURSE_TO_ADD',
};